#!/usr/bin/env php
<?php

namespace Kyoushu\Genny;

use Kyoushu\Genny\Bundle\Console\Application;
use Kyoushu\Genny\Bundle\GennyBundle;

require_once(__DIR__ . '/../vendor/autoload.php');

$kernel = new Kernel('dev', true);
$kernel->boot();

$application = new Application($kernel->getContainer());
/** @var GennyBundle $bundle */
$bundle = $kernel->getBundle('GennyBundle');
$bundle->registerCommands($application);

$application->run();