
services:

    genny.console.application:
        class: Kyoushu\Genny\Bundle\Console\Application
        arguments: [ @service_container ]

    genny.console.command.page_generator:
        class: Kyoushu\Genny\Bundle\Console\Command\PageGeneratorCommand
        tags:
            - { name: genny.console.command }

    genny.console.command.watch:
            class: Kyoushu\Genny\Bundle\Console\Command\WatchCommand
            tags:
                - { name: genny.console.command }

    genny.twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [ "%genny.templates_dir%" ]

    genny.twig:
        class: Twig_Environment
        arguments: [ @genny.twig.loader ]

    genny.page_generator:
        class: Kyoushu\Genny\Bundle\Generator\PageGenerator
        arguments: [ @genny.twig, "%genny.pages_dir%", "%genny.dist_dir%", "%genny.templates_dir%" ]
